version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrongPassword"
    ports:
      - "1433:1433"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  flask:
    build:
      context: ../backend/
      dockerfile: Dockerfile.flask
    ports:
      - "5000:5000"

